FROM ubuntu:18.04

RUN apt-get update && apt-get install -y python3.6 python3.6-dev python3-pip
RUN ln -sfn /usr/bin/python3.6 /usr/bin/python3 && ln -sfn /usr/bin/python3 /usr/bin/python && ln -sfn /usr/bin/pip3 /usr/bin/pip

RUN apt-get install libffi-dev ca-certificates curl -y

RUN pip install --upgrade pip
RUN pip install grpcio grpcio-tools

RUN mkdir -p /openfx/executor
WORKDIR /openfx/executor

COPY . .

RUN pip install -r requirements.txt
